title = "HardPy TOML config"
tests_dir = "dialog_box"

[database]
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000

[socket]
host = "localhost"
port = 6525
