name: Lint
on:
  workflow_call: # allow this workflow to be called from other workflows
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          only_warn: 1
