name: Lint
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
