name: Test

on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      python-version:
        description: 'Python version to test against'
        required: false
        default: '3.10'
        type: string
      pytest-version:
        description: 'Pytest version to test against'
        required: false
        default: ''
        type: string
  workflow_dispatch: # allow manual trigger
    inputs:
      python-version:
        description: 'Python version to test against'
        required: false
        default: '3.10'
        type: string
      pytest-version:
        description: 'Pytest version to test against'
        required: false
        default: ''
        type: string

permissions:
  checks: write

jobs:
  test:
    name: PyTest (Python ${{ inputs.python-version }}, Pytest ${{ inputs.pytest-version || 'default' }})
    runs-on: ubuntu-latest
    services:
      db:
        image: couchdb:3.4
        env:
          COUCHDB_USER: dev
          COUCHDB_PASSWORD: dev
        ports:
          - 5984:5984
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        architecture: 'x64'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install .[tests]
        if [ -n "${{ inputs.pytest-version }}" ]; then
          python -m pip install pytest==${{ inputs.pytest-version }}
        fi

    - name: Run PyTest
      uses: dariocurr/pytest-summary@main
      with:
        options: tests
        show: "all"